---
- hosts: all
  tasks:
    - name: Copy pcap file from ControlNode
      fetch:
        src: /home/corneta/Downloads/cap.pcap
        dest: /home/corneta/HOA_8.1/
        flat: yes

- hosts: localhost
  connection: local
  gather_facts: true
  become_user: root
  tasks:
    - name: Show Extractionn
      command: "tcpflow -r /home/corneta/HOA_8.1/cap.pcap -o /home/corneta/HOA_8.1"
      args:
        creates: "/home/corneta/HOA_8.1/executable.exe"

    - name: Debug file
      command: "cat /home/corneta/HOA_8.1/report.xml"
      register: cat_output
      changed_when: false

    - debug:
        var: cat_output.stdout_lines
